# DEVELOPMENT ENVIRONMENT ONLY - NOT FOR PRODUCTION USE
# start with docker compose up

version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - ./.env
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    command: python -m flask run --host=0.0.0.0 --port=8080